[toolchain]
anchor_version = "1.1.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
treasury_router = "5mEQEoksSyTMJifw88UWGna81bY6ghWPJqHNFfDWcYD3"
rbvr_oracle_adapter = "E5T6hAp6pTE9iZvwMMRaUD7kDC3UkJWiiqi24fJf3sqx"

[provider]
cluster = "localnet"
wallet = "/home/alec_elliott/rocket-beaver-dev/keys/local-deployment.json"

[scripts]
test = "npm run test:integration"

[workspace]
members = [
    "programs/treasury-router",
    "oracle-adapter/programs/rbvr-oracle-adapter"
]
